### ISSUE TITLE
Launching server cquery failed on macos

### ISSUE THREAD

**Issue by swustcfl** [cquery-project/vscode-cquery#10]
cquery config is 
    "cquery.launch.workingDirectory": "~/Documents/github/cquery/build/",
    "cquery.launch.command": "release/bin/cquery",
    "cquery.cacheDirectory": "~/Documents/github/vscode-cquery",
    "cquery.launch.autoRestart": true,
    "cquery.launch.notifyOnCrash": true,

cquery bin path is /Users/jasonchen/Documents/github/cquery/build/release/bin

after vscode reload  window  , i  run into issues (Launching server using command release/bin/cquery failed.) 

cquery version is the tag of v20180203

i try to solve this problem，but failed。Any suggestions? thx

**Comment by jiegec** [comment]
The path should be absolute.

**Comment by jacobdufault** [comment]
working dir should be "/Users/jasonchen/Documents/github/cquery/build"

**Comment by MaskRay** [comment]
`cquery.launch.workingDirectory` should have no use now and it is confusing.

**Comment by jacobdufault** [comment]
What? It is still needed to specify where cquery server binary is located.

**Comment by MaskRay** [comment]
e.g. cquery.el calls it `cquery-executable` (combined)

**Comment by jacobdufault** [comment]
Yea, that's what we should do in vscode as well. But for the time being it is still relevant.

**Comment by swustcfl** [comment]
thx!
