### ISSUE TITLE
Semantic highlighting is messed up

### ISSUE THREAD

**Issue by HighCommander4** [cquery-project/vscode-cquery#15]
Some kinds of symbols are colored with the wrong color, as if the symbol kinds got mixed up somehow.

**Comment by HighCommander4** [comment]
Looks like the server changed its representation of symbol kinds from ClangSymbolKind to lsSymbolKind, which has slightly different kinds in a different order. Meanwhile the client's SemanticSymbolKind still corresponds to ClangSymbolKind.

**Comment by MaskRay** [comment]
Yes, `ClangSymbolKind` has been removed.

https://github.com/cquery-project/emacs-cquery/blob/master/cquery-semantic-highlighting.el#L188 this may help

**Comment by HighCommander4** [comment]
I have a fix for this locally, but I will wait until https://github.com/cquery-project/cquery/pull/470 merges, to make sure the changes here correspond to that.

**Comment by jacobdufault** [comment]
Merged, please upload the PR :)

**Comment by antcodd** [comment]
Would be nice to get a release for this issue. The inconsistent and missing highlighting is a bit confusing.

**Comment by MaskRay** [comment]
And `$cquery/callTreeInitial` -> `$cquery/callHierarchyInitial`

**Comment by jacobdufault** [comment]
> Would be nice to get a release for this issue. The inconsistent and missing highlighting is a bit confusing.

I've pushed a new release. Make sure to also update the cquery binary, as the call tree / type hierarchy have been renamed to call hierarchy and inheritance hierarchy - the underlying API has changed.

**Comment by antcodd** [comment]
Thanks! Seems to be working properly.
