### ISSUE TITLE
command 'cquery.freshenIndex' not found (and others)

### ISSUE THREAD

**Issue by bdeeming** [cquery-project/vscode-cquery#22]
I have followed the instructions from the wiki to setup the cquery extension for VS Code. When I run any of the commands using the command pallet such as '_cquery: Freshen Index_' I get an error notification: _command 'cquery.freshenIndex' not found_.
This appears to be true for all of the cquery commands.

There does not appear to be an output panel log associated with the cquery extension as eluded to by the wiki 

> If you run into issues, you can view debug output by running the (F1) View: Toggle Output command and opening the cquery output section.

However in the colsole log in devtools there is:
`/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Activating extension 'cquery-project.cquery' failed: Cannot find module './callHierarchy'. (at Object.showMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:690:704))`

A quick look in the `~/.vscode/extensions/cquery-project.cquery-0.0.10/out` dir revealed that there is in fact no `callHierarchy.js` file (`inheritanceHierarchy.js` _is_ there however).

**Comment by jacobdufault** [comment]
You installed cquery from the marketplace? It sounds like a corrupt installation given that `callHierarchy` is missing.

**Comment by bdeeming** [comment]
Indeed from the market place. I will try reinstalling to see if that makes a difference.

**Comment by bdeeming** [comment]
No joy, still missing. Perhaps its corrupted on the marketplace end?

**Comment by bdeeming** [comment]
Built from src is working fine.

**Comment by jacobdufault** [comment]
I use the marketplace install and it seems to work well. Not sure - vscode has gotten corrupted on me in the past so maybe it is caching the corrupted install.

**Comment by bdeeming** [comment]
I think this might be the result of a race condition in the VS Code extension installation process that allows the user to click 'Reload' before all files have been installed. 
I have installed it both from the market place and directly using the vsix file, and have both succeeded and failed with both of them, and not in a reproducible way. Anyways it's not a problem with the package of this extension so I'll close this issue.
Thanks for your help, and a great extension.
