### ISSUE TITLE
Remote cquery language server support

### ISSUE THREAD

**Issue by TwIStOy** [cquery-project/vscode-cquery#23]
vscode-cquery now only support local cquery language server. But sometimes setting up a compilation environment locally is a complicated matter. So If the vscode-cquery can connect to a remote cquery language server?

**Comment by jacobdufault** [comment]
I think this is a more general problem of how remote language servers could work. I have some thoughts but it would work for more than just cquery (ie, tunnel cquery stdin/stdout using ssh).

**Comment by TwIStOy** [comment]
It seems that language client in vscode has supported to communicate with language server via socket. I found a example, it may be helpful.
https://github.com/itemis/xtext-languageserver-example/blob/master/vscode-extension/src/extension.ts

**Comment by jacobdufault** [comment]
Most things work if you use Live Share (see https://github.com/MicrosoftDocs/live-share/issues/314).

**Comment by jacobdufault** [comment]
Notably, no cquery extensions work (ie, call tree).

**Comment by phord** [comment]
Live-share doesn't support headless servers yet and has extensive dependencies.  Surely there's a way to extend language servers across a network without installing .Net and a bazillion DLLs.  In my case, I want to share my cluster of build machines to offload the cquery work. Why must the editor get involved directly?

Maybe I need to refresh my memory on the language-server interface to see how to extend it across ssh, like you hinted.

**Comment by phord** [comment]
Actually, it looks like "ssh remote cquery" should be sufficient.  I suppose it requires that the path to the code on the remote server is identical to the project path on the local server.  But ssh is happy to pipe stdin/stdout for you. I created a script named `cquery` in my path, like so:

    #!/bin/sh
    ssh remote-server "cd $(pwd) ; cquery"

You still need some mechanism to sync the files from the local to the remote, though.

**Comment by danleepw** [comment]
Hi @phord , actually how do you use the cquery on remote server? I am trying to do it with vscode by putting the script as the launch command. However, vscode seems not working with it.

**Comment by sergei-dyshel** [comment]
@danleepw 
I'm have this script-based hack flawlessly working with both `cquery` and `ccls`. What output do you get in `cquery` output panel?

**Comment by danleepw** [comment]
@sergei-dyshel , do you mean the stdout of cquery? If yes, it can show a proper json output. However, my vscode can't talk with it and show "cquery:loading" in the status bar

**Comment by sergei-dyshel** [comment]
Can you share stdout you get and also contents of log file (use `-log-file=` for that)?

**Comment by danleepw** [comment]
--- stdout ---
2018-11-13 15:48:49.280 (   0.000s) [     9FAC2740]        loguru.hpp:2049     0| Logging to '/tmp/cquery.log', mode: 'w', verbosity: 9
Content-Length: 152

{"jsonrpc":"2.0","method":"$cquery/progress","params":{"indexRequestCount":0,"doIdMapCount":0,"onIdMappedCount":0,"onIndexedCount":0,"activeThreads":0}}

--- end of  stdout ---

--- log file ---
File verbosity level: 9
date       time         ( uptime  ) [ thread name/id]              file:line     v|
2018-11-13 15:48:49.280 (   0.000s) [     9FAC2740]        loguru.hpp:2049     0| Logging to '/tmp/cquery.log', mode: 'w', verbosity: 9
(   0.000s) [main thread  ]        loguru.hpp:1887  | arguments: ./cquery --log-file /tmp/cquery.log --language-server
(   0.000s) [main thread  ]        loguru.hpp:1890  | Current dir: /usr/local/bin/cquery/bin
(   0.000s) [main thread  ]        loguru.hpp:1892  | stderr verbosity: -1
(   0.000s) [main thread  ]        loguru.hpp:1893  | -----------------------------------


--- end of log file ---

**Comment by danleepw** [comment]
The question i have is: how does vscode communicate with cquery? by network socket, ipc, or ?

**Comment by sergei-dyshel** [comment]
pipe
-- 
Regards,
Sergei Dyshel
