### ISSUE TITLE
Many settings don't work

### ISSUE THREAD

**Issue by neckbosov** [cquery-project/vscode-cquery#28]
I can't disable diagnostics and snippet insertion in settings in Visual Studio Code.

**Comment by jacobdufault** [comment]
Fixed in c6e992e46fd6bc53682291a8ffbadcc1ac9f9273 and 987a4ee48cf38df0bd523e2b82fb498b14acb9c0

**Comment by neckbosov** [comment]
No, I still can't disable snippet insertion

**Comment by jacobdufault** [comment]
You need to update cquery and the extension.

**Comment by neckbosov** [comment]
Wow, great! You make great project, thanks! 
--
Отправлено из Mail.Ru для Android вторник, 08 мая 2018г., 18:38 +03:00 от Jacob Dufault  notifications@github.com :
