### ISSUE TITLE
add shortcut for function autocompletion without arguments substitution

### ISSUE THREAD

**Issue by Yanpas** [cquery-project/vscode-cquery#31]
Currently when you autocomplete function `void foo(int a, int b)` **a** and **b** will be substituted. There are popular shortcuts (don't remeber which is used in vs code) like shift+enter that only completes function name

**Comment by Yanpas** [comment]
Or at least add option that will turn off argument sunstitution

**Comment by jacobdufault** [comment]
You can use the following setting to turn it off in vscode:

```
  "cquery.completion.enableSnippetInsertion": false,
```

**Comment by Yanpas** [comment]
This setting doesn't have any effect for me, I'm using cquery 40e57e46d0e681c873e9aa17d2df5930d095b8b8

**Comment by jacobdufault** [comment]
Please update cquery
