### ISSUE TITLE
cquery process is not killed on exit

### ISSUE THREAD

**Issue by Yanpas** [cquery-project/vscode-cquery#36]
STR:
open, close, open, close, open cquery project via 'open folder' in vs code (or even restart vs code).

Processes count will only increase (`ps ax | grep cquery` or `pgrep -f cquery`).

OS ubuntu 18.04
cquery version `94a1a5c9d1911e919da3f5ab085fa3b938854505`

**Comment by jacobdufault** [comment]
94a1a5c9d1911e919da3f5ab085fa3b938854505 is decently old, does this happen on master?

**Comment by Yanpas** [comment]
Yes, it's fixed in master
