### ISSUE TITLE
Unable to save the file

### ISSUE THREAD

**Issue by rteja** [cquery-project/vscode-cquery#5]
On very large code base, often unable to save the file when using Cquery. File gets locked until I disable cquery plugin for the workspace.

**Comment by jacobdufault** [comment]
That's very strange, cquery should not be touching the file outside of copying it. What platform are you on?

Random question, do you have the microsoft c++ extension installed?

**Comment by rteja** [comment]
I am working on Windows 10. Yes I do have microsoft c++ extension enabled along with cquery.

**Comment by jacobdufault** [comment]
Please disable the microsoft c++ extension and see if that fixes the problem. Microsoft c++ indexing interacts very poorly with cquery (it makes everything slow).

**Comment by rteja** [comment]
Yes, running only one of the plugins, I do not have this problem.
