### ISSUE TITLE
Watch LSP traffic between vscode-cquery and cquery server?

### ISSUE THREAD

**Issue by HighCommander4** [cquery-project/vscode-cquery#65]
Is there a place to watch the LSP traffic between vscode-cquery and the cquery server?

My recollection is that this used to be logged in the "cquery" output window, but it no longer is. The server doesn't log it either, only things like `[e2e] Running textDocument/documentHighlight took 0.95ms`.

**Comment by jacobdufault** [comment]
`cquery --record <path>` should do the trick

https://github.com/cquery-project/cquery/blob/master/src/command_line.cc#L69-L106
