### ISSUE TITLE
Option to disable autocomplete

### ISSUE THREAD

**Issue by ginkoshi** [cquery-project/vscode-cquery#74]
Cquery has an amazing feature I cannot find anywhere else so far: Rainbow Semantic Highlighting.

I really, really want to use this, but for my project I find cquery's autocomplete to be painfully slow.
I opted to start using clangd, which seems to be instant! However, if cquery is enabled, it overrides clangd.. but if it is disabled I won't get the glorious highlighting!

Essentially, I want to use this just for the highlighting! Is that possible?

**Comment by jacobdufault** [comment]
Give https://github.com/jacobdufault/lsp-filter a try.

**Comment by ginkoshi** [comment]
That worked! Thanks for the suggestion!
It would be awesome if it could be as simple as a setting someday, though!
